ALTER TABLE users
  ADD COLUMN IF NOT EXISTS wager_required_nanoton BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS wager_progress_nanoton BIGINT NOT NULL DEFAULT 0;

ALTER TABLE platform_withdrawal_settings
  ADD COLUMN IF NOT EXISTS deposit_wager_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS crash_wager_target DOUBLE PRECISION NOT NULL DEFAULT 2.0;
