package domain

import "errors"

var (
	ErrInvalidAmount     = errors.New("invalid amount")
	ErrInsufficientFunds = errors.New("insufficient balance")
	ErrRoundNotOpen      = errors.New("round not accepting bets")
	ErrRoomFull          = errors.New("room is full")
	ErrNotFound          = errors.New("not found")
	ErrForbidden         = errors.New("forbidden")
	ErrAlreadyListed     = errors.New("item already listed")
	ErrWalletNotLinked   = errors.New("wallet not linked")
	ErrInvalidWallet     = errors.New("invalid wallet address")
	ErrTransferPending   = errors.New("transfer already pending")
	ErrTransferExpired   = errors.New("transfer expired")
	ErrTransferNotFound  = errors.New("transfer not found")
	ErrDuplicateRequest  = errors.New("duplicate request")
	ErrAlreadyJoined     = errors.New("already joined")
	ErrChainUnavailable  = errors.New("chain verification unavailable")
	ErrBetLimitExceeded  = errors.New("bet limit exceeded")
	ErrDailyWinCap       = errors.New("daily win cap reached")
	ErrUserBanned        = errors.New("account suspended")
	ErrGameDisabled      = errors.New("game disabled")
	ErrPromoInvalid         = errors.New("invalid promo code")
	ErrPromoExpired         = errors.New("promo code expired")
	ErrPromoExhausted       = errors.New("promo code exhausted")
	ErrPromoAlreadyRedeemed  = errors.New("promo code already redeemed")
	ErrPromoFundsRestricted  = errors.New("promo funds cannot be used on market")
	ErrPromoInUse            = errors.New("promo code has redemptions")
)
