package domain

import "errors"

var (
	ErrInvalidAmount          = errors.New("некорректная сумма")
	ErrInsufficientFunds      = errors.New("недостаточно средств")
	ErrRoundNotOpen           = errors.New("ставки больше не принимаются")
	ErrNotFound               = errors.New("не найдено")
	ErrForbidden              = errors.New("доступ запрещён")
	ErrAlreadyListed          = errors.New("предмет уже выставлен на продажу")
	ErrWalletNotLinked        = errors.New("кошелёк не подключён")
	ErrInvalidWallet          = errors.New("некорректный адрес кошелька")
	ErrTransferPending        = errors.New("уже есть активная операция")
	ErrTransferExpired        = errors.New("время операции истекло")
	ErrTransferNotFound       = errors.New("операция не найдена")
	ErrDuplicateRequest       = errors.New("повторный запрос")
	ErrChainUnavailable       = errors.New("проверка сети TON недоступна")
	ErrBetBelowMinimum        = errors.New("ставка ниже минимума")
	ErrBetLimitExceeded       = errors.New("превышен лимит ставки")
	ErrDailyWinCap            = errors.New("достигнут дневной лимит выигрыша")
	ErrUserBanned             = errors.New("аккаунт заблокирован")
	ErrGameDisabled           = errors.New("игра временно недоступна")
	ErrBetsPaused             = errors.New("ставки временно не принимаются")
	ErrMarketDisabled         = errors.New("маркет временно недоступен")
	ErrGiftDepositDisabled    = errors.New("депозит подарками временно недоступен")
	ErrMaintenance            = errors.New("техническое обслуживание")
	ErrPromoInvalid           = errors.New("недействительный промокод")
	ErrPromoExpired           = errors.New("промокод истёк")
	ErrPromoExhausted         = errors.New("промокод исчерпан")
	ErrPromoAlreadyRedeemed   = errors.New("промокод уже использован")
	ErrPromoInUse             = errors.New("у промокода есть активации")
	ErrChannelNotSubscribed   = errors.New("нужна подписка на канал")
	ErrGiftNotAvailable       = errors.New("подарок недоступен для ставки")
	ErrGiftValueMismatch      = errors.New("стоимость подарка не подходит для ставки")
	ErrStakingPoolFull        = errors.New("пул стейкинга заполнен")
	ErrStakingPersonalLimit   = errors.New("личный лимит стейкинга исчерпан — выполните задания чтобы увеличить лимит")
	ErrGiftAlreadyStakedEpoch = errors.New("подарок уже застейкан сегодня")
	ErrCaseUnavailable        = errors.New("кейс недоступен")
	ErrCasesDisabled          = errors.New("кейсы временно недоступны")
	ErrCaseDailyUsed          = errors.New("ежедневный кейс уже открыт")
	ErrCaseCooldown           = errors.New("кейс можно открыть раз в 24 часа")
	ErrCaseNoLoot             = errors.New("у кейса нет призов")
	ErrCaseNameTagRequired    = errors.New("добавьте тег в имя Telegram")
	ErrCaseShareRequired      = errors.New("поделитесь ссылкой чтобы открыть кейс")
	ErrUnbackedBuyback        = errors.New("виртуальный приз кейса нельзя продать по рыночной цене — продайте по цене кейса или выведите подарок")
	ErrGiftNotInBotCustody    = errors.New("подарок не задепозичен в бота — продажа недоступна")
	ErrCaseClaimCashoutOnly   = errors.New("кейсовый приз продаётся только по гарантированной цене кейса")
	ErrAdminPasswordNotSet    = errors.New("пароль админки не настроен")
	ErrAdminPasswordInvalid   = errors.New("неверный пароль")
	ErrAdminActorMissing      = errors.New("сначала зайдите в Mini App под admin Telegram ID")
	ErrAdminLoginPending      = errors.New("ожидаем подтверждение входа в Telegram")
	ErrAdminLoginDenied       = errors.New("вход отклонён")
	ErrAdminLoginExpired      = errors.New("время подтверждения истекло")
	ErrAdminLoginNotFound     = errors.New("запрос на вход не найден")
	ErrQuestNotReady          = errors.New("задание ещё не выполнено")
	ErrQuestAlreadyClaimed    = errors.New("награда уже получена")
	ErrQuestBonusLocked       = errors.New("сначала выполните все задания")
	ErrQuestUnavailable       = errors.New("задание недоступно")
	ErrCaseEntitlementMissing = errors.New("нет бесплатного открытия этого кейса")
	ErrInvalidCampaign        = errors.New("некорректная кампания")
	ErrCampaignCodeTaken      = errors.New("код кампании уже занят")
)
