package domain

import "errors"

var (
	ErrInvalidAmount     = errors.New("некорректная сумма")
	ErrInsufficientFunds = errors.New("недостаточно средств")
	ErrRoundNotOpen      = errors.New("ставки больше не принимаются")
	ErrRoomFull          = errors.New("комната уже заполнена")
	ErrNotFound          = errors.New("не найдено")
	ErrForbidden         = errors.New("доступ запрещён")
	ErrAlreadyListed     = errors.New("предмет уже выставлен на продажу")
	ErrWalletNotLinked   = errors.New("кошелёк не подключён")
	ErrInvalidWallet     = errors.New("некорректный адрес кошелька")
	ErrTransferPending   = errors.New("уже есть активная операция")
	ErrTransferExpired   = errors.New("время операции истекло")
	ErrTransferNotFound  = errors.New("операция не найдена")
	ErrDuplicateRequest  = errors.New("повторный запрос")
	ErrAlreadyJoined     = errors.New("вы уже в этой комнате")
	ErrChainUnavailable  = errors.New("проверка сети TON недоступна")
	ErrBetLimitExceeded  = errors.New("превышен лимит ставки")
	ErrDailyWinCap       = errors.New("достигнут дневной лимит выигрыша")
	ErrUserBanned        = errors.New("аккаунт заблокирован")
	ErrGameDisabled      = errors.New("игра временно недоступна")
	ErrPromoInvalid         = errors.New("недействительный промокод")
	ErrPromoExpired         = errors.New("промокод истёк")
	ErrPromoExhausted       = errors.New("промокод исчерпан")
	ErrPromoAlreadyRedeemed  = errors.New("промокод уже использован")
	ErrPromoFundsRestricted  = errors.New("бонус нельзя тратить на маркет")
	ErrPromoInUse            = errors.New("у промокода есть активации")
	ErrPromoWagerPending     = errors.New("сначала отыграйте активный бонус")
	ErrChannelNotSubscribed  = errors.New("нужна подписка на канал")
	ErrWheelNoSpins          = errors.New("нет доступных прокрутов")
	ErrWheelUnavailable      = errors.New("колесо временно недоступно")
	ErrGiftNotAvailable      = errors.New("подарок недоступен для ставки")
	ErrGiftValueMismatch     = errors.New("стоимость подарка не подходит для ставки")
	ErrStakingPoolFull       = errors.New("пул стейкинга заполнен")
	ErrStakingPersonalLimit  = errors.New("личный лимит стейкинга исчерпан — выполните задания чтобы увеличить лимит")
	ErrGiftAlreadyStakedEpoch = errors.New("подарок уже застейкан на этой неделе")
)
